### ISSUE TITLE
ModuleNotFoundError: No module named 'NDIlib.NDIlib'

### ISSUE THREAD

**Issue by vizart-vj** [ningxiaoxiao/comfyui-NDI#7]
I'm using a latest version of ComfyUi portable. Python 3.11.9 

Loading ComfyUI-NDI nodes begin----------
Traceback (most recent call last):
  File "I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-NDI\__init__.py", line 13, in <module>
    import NDIlib.NDIlib as ndi
  File "I:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\NDIlib\__init__.py", line 6, in <module>
    from .NDIlib import *
ModuleNotFoundError: No module named 'NDIlib.NDIlib'

Cannot import I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-NDI module for custom nodes: No module named 'NDIlib.NDIlib'

**Comment by ningxiaoxiao** [comment]
First, you need to know how to install pip packages. Then, you need to solve the installation of the ndi-python library.

**Comment by ningxiaoxiao** [comment]
https://github.com/buresu/ndi-python    This is the library of ndi-python. Hope it can help you.

**Comment by keno-log** [comment]
no ndi-python for Python >=3.11, anybody can help?
