### ISSUE TITLE
Error Importing

### ISSUE THREAD

**Issue by Samuel780000** [ningxiaoxiao/comfyui-NDI#8]
Getting an error on importing custom nodes :

0.0 seconds (IMPORT FAILED): C:\Users\me\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-NDI

**Comment by Samuel780000** [comment]
Cannot import C:\Users\me\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-NDI module for custom nodes: No module named 'cv2'

I've tried pip install opencv-python, but didn't solve !

**Comment by Samuel780000** [comment]
going deeper :
if i try :
ComfyUI_windows_portable\python_embeded\python.exe -m pip install ndi-python

getting error : ERROR: Failed building wheel for ndi-python

**Comment by ningxiaoxiao** [comment]
This error is an issue with version 3.10. It seems ndi-python does not support versions above 3.10. I hope it will fix this problem.I don't have the energy to study the ndi-python library. Maybe I will update this later.

**Comment by Samuel780000** [comment]
> This error is an issue with version 3.10. It seems ndi-python does not support versions above 3.10. I hope it will fix this problem.I don't have the energy to study the ndi-python library. Maybe I will update this later.

I installed Python 3.9, followed all the installation process from your instructions (no errors), but then, once i start ComfyUI:

Loading ComfyUI-NDI nodes begin----------
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-NDI\__init__.py", line 13, in <module>
    import NDIlib as ndi
ModuleNotFoundError: No module named 'NDIlib'
